### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hogredan**
Links to the results for 2020-2023 added

### CODE REVIEW

**Comment by fabiovinci** [comment]
Dear @hogredan,

thank you for the update.

**Comment by fabiovinci** [comment]
Dear @hogredan,

I merged the PR but I verified now that also the 2019 link was changed from [Indicator 2019](http://cdr.eionet.europa.eu/de/eu/inspire/monitoring/envxnpla/) to [Indicator 2019](https://inspire-geoportal.ec.europa.eu/mr/mr2019_details.html?country=de).

This appears to be incorrect.
Could you please verify?

**Comment by hogredan** [comment]
Dear @fabiovinci ,

I have copied the 2019 link from @jescriu 's comment in [Issue #174 of the Geoportal helpdesk](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/174#issuecomment-2233843351). Thus, the link should be correct.

**Comment by fabiovinci** [comment]
Thank you for the reply.
When I looked at it the link wasn't working, now it works.

**Pull request merged**
