### PR TITLE
Update AT-Country_fiche-2024.md

### PR DESCRIPTION
**Pull request by fabiovinci**
- Fixed typos
- Changed image encoding to be visible on GitHub pages
- Updated encoding of the URLs to be visible on GitHub pages

### CODE REVIEW

**Comment by fabiovinci** [comment]
Dear @oberseri,
we have made some improvements to your country fiche.
Could you please review them and confirm if they are acceptable to you?
Many thanks.

**Comment by oberseri** [comment]
Dear @fabiovinci 
so many thanks for fixing the typos (sorry for them) and changing the image encoding!!!
Regarding the URLs, we would prefer "visible" URLs (so to say as a brand), possibly without leading "https://";
see the attached PDF as example

Thanks again and best regards Erik

[inspirecountryficheaustria_2024_en_v4.pdf](https://github.com/INSPIRE-MIF/INSPIRE-in-your-Country/files/14848040/inspirecountryficheaustria_2024_en_v4.pdf)

**Comment by fabiovinci** [comment]
Dear @oberseri,

I changed the encoding of the links to make them "visible" as in the pdf file.
Everything seems ok so I will proceed with the merge of the PR.

**Comment by oberseri** [comment]
Thanks Fabio!
@fabiovinci

**Pull request merged**
